# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: app.m4d.ibm.com/v1alpha1
kind: Blueprint
metadata:
  name: m4d-sample
  labels:
    app: "m4d-sample"
spec:
  data_set: myCatalogue
  plugins:
    - name: Encryption
      id: ENC
      version: "1.0"
      status: DEV
      actions:
        - Encrypt
      source:
        protocol: GRPC
        dataFormat: CSV
        schema: jsonSchema
      sink:
        protocol: GRPC
        dataFormat: CSV
        schema: jsonSchema
      image: encrypt.img
      plugin_types:
        - Transform      
      arguments:
        seed: "1234"
        column: ID
    - name: Mask
      image: masking.img
      id: MSK
      version: "6.8"
      status: TEST
      actions:
        - Mask
      source:
        protocol: GRPC
        dataFormat: CSV
        schema: jsonSchema
      sink:
        protocol: GRPC
        dataFormat: CSV
        schema: jsonSchema
      plugin_types:
        - Transform      
      arguments:
        column: Phone
        mask: "***"
