# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: motion.m4d.ibm.com/v1alpha1
kind: BatchTransfer
metadata:
  name: batchtransfer-sample
spec:
  source:
    database:
      db2URL: "jdbc:db2://db1.psvc-dev.zc2.ibm.com:50602/DHUBS:sslConnection=true;"
      table: "TESTDATA.SMALL"
      user: myuser
      password: "mypassword"
  destination:
    s3:
      endpoint: "s3.us-south.cloud-object-storage.appdomain.cloud"
      region: "us-south"
      bucket: "my-bucket"
      accessKey: MYACCESSKEYKEY
      secretKey: MYSECRETKEY
      objectKey: "testdata.small.parq"
      dataFormat: "parquet"
  transformation:
    - name: "Remove com_name name"
      action: "RemoveColumns"
      columns: ["com_name"]
      options:
        key: value
    - name: "Digest synonym"
      action: "DigestColumns"
      columns: ["synonym"]
      options:
        algo: "md5"
  image: datamover:1.0-SNAPSHOT
  imagePullPolicy: "IfNotPresent"
#  schedule: "*/1 * * * *"