# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: motion.m4d.ibm.com/v1alpha1
kind: StreamTransfer
metadata:
  name: streamtransfer-sample
spec:
  source:
    kafka:
      kafkaBrokers: "none.local:9292"
      schemaRegistryURL: "http://none.local:8080"
      user: "kafka"
      kafkaTopic: "myTopic"
      createSnapshot: false
      securityProtocol: "SASL_SSL"
      saslMechanism: "SCRAM-SHA-512"
      keyDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      sslTruststore: DEADBEEF # Truststore as base64 encoded
      sslTruststoreLocation: /etc/ca/ca.p12
      sslTruststorePassword: changeme # password of truststore (Can be taken from vault)
      vaultPath: "/v1/secret/data/kafka/m4d"
  destination:
    s3:
      endpoint: "s3.eu-gb.cloud-object-storage.appdomain.cloud"
      region: "eu-gb"
      bucket: "m4d-test-bucket"
      objectKey: "kafka-test.parq"
      dataFormat: "parquet"
      vaultPath: "/v1/secret/data/cos/m4d"
  transformation: []
  secretProviderURL: "http://secret-provider.secret-provider.svc.cluster.local:5555/get-secret"
  secretProviderRole: demo