# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

kind: Service
apiVersion: v1
metadata:
  name: {{ include "m4d-proxy.instance" . }}
  labels:
    {{- include "m4d-proxy.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
