# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "m4d-proxy.instance" . }}
  labels:
    {{- include "m4d-proxy.labels" . | nindent 4 }}
spec:
  gateways:
  - mesh
  - {{ include "m4d-proxy.instance" . }}
  hosts:
  - {{ include "m4d-proxy.instance" . }}
  - {{ include "m4d-proxy.fqdn" . }}
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: {{ include "m4d-proxy.egressgatewayFqdn" . }}
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - bucket1
      port: 80
    rewrite:
      authority: {{ .Values.proxy.host }}
    route:
    - destination:
        host: {{ .Values.proxy.host }}
        port:
          number: 443
      weight: 100
