# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# permissions to do viewer batchtransfers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: batchtransfer-viewer-role
rules:
- apiGroups:
  - motion.m4d.ibm.com
  resources:
  - batchtransfers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - motion.m4d.ibm.com
  resources:
  - batchtransfers/status
  verbs:
  - get
