# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: datamover-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - events/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch