# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# Adds namespace to all resources.
namespace: m4d-system

bases:
- ../default

# Minikube's registry is found at a different url than the default openshift registry
# This hack creates services that expose the registry at the common open shift endpoint
# image-registry.openshift-image-registry.svc:5000
resources:
- openshift-registry-compatibility.yaml

patchesStrategicMerge:
- manager_patch.yaml