# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-image-registry
spec:
  finalizers:
  - kubernetes

### Hack to expose registry on the same port as openshift does
---
apiVersion: v1
kind: Service
metadata:
  name: registry-5000
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    actual-registry: "true"
    kubernetes.io/minikube-addons: registry
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: registry-5000-np
  namespace: kube-system
spec:
  type: NodePort
  selector:
    actual-registry: "true"
    kubernetes.io/minikube-addons: registry
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: image-registry
  namespace: openshift-image-registry
spec:
  type: ExternalName
  externalName: registry-5000.kube-system.svc.cluster.local
  ports:
  - protocol: TCP
    targetPort: 5000
    port: 5000
