name: Website Deploy
on:
  push:
  pull_request:
jobs:
  website-deploy:
    runs-on: ubuntu-latest
    env:
      QUICKSTART_FILE: './docs/get-started/deploy-version.txt'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Material for MkDocs
        run: |
          pip install mkdocs-material=="8.*"
          pip install mike
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "noreply@github.com"
      - id: version
        name: Infer version
        run: echo ::set-output name=version::$(cut -d '.' -f 1,2 <<< "${GITHUB_REF#refs/*/}")
      - name: Build and Deploy (dev)
        working-directory: ./site
        uses: bluwy/substitute-string-action@v1
        if: steps.version.outputs.version == 'master'
        with:
          _input-file: $env.QUICKSTART_FILE
          _format-key: '%%key%%'
          _output-file: $env.QUICKSTART_FILE
          xxxRelease: ""
        #run: mike deploy --push --remote origin --branch site dev
        run: echo $env.QUICKSTART_FILE
      - name: Build and Deploy (tag)
        uses: bluwy/substitute-string-action@v1
        if: steps.sub.outputs.result != 'master'
        working-directory: ./site
        with:
          _input-file: $env.QUICKSTART_FILE
          _output-file: $env.QUICKSTART_FILE
          _format-key: '%%key%%'
          xxxRelease: "--version ${{ steps.sub.outputs.note }}"
        # run: mike deploy --push --update-aliases --remote origin --branch site ${{ steps.version.outputs.version }} latest
        run: echo $env.QUICKSTART_FILE
